<?php

namespace Basicperf\MetricsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FrontendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrontendRepository extends EntityRepository
{
	public function loadtime($data){

	}
}
